[tool.poetry]
name = "sundash"
version = "0.1.0"
description = ""
authors = ["Danil Tryapchev <ruthus18@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
starlette = "^0.31.1"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
loguru = "^0.7.2"

[tool.poetry.group.dev.dependencies]
ipython = "^8.16.1"
ipdb = "^0.13.13"
flake8 = "^6.1.0"
isort = "^5.12.0"
poethepoet = "^0.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
